services:
  # Service 1: PostgreSQL Database Container
  postgres_db:
    image: postgres:16
    container_name: de_postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"  # Maps local port 5433 to container port 5432 so like we basiocally make a tunnel from windows to docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # Service 2: python script runner container
  etl_pipeline:
    build: .
    container_name: de_python_pipeline
    environment:
      DB_HOST: postgres_db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data: